# Numpy

In [1]:
a = 1,2,3

In [5]:
print(a)
print(type(a))

(1, 2, 3)
<class 'tuple'>


In [7]:
import numpy as np

In [8]:
l = [2,3,4]
arr1 = np.array(l)
print(arr1)

[2 3 4]


In [11]:
j = [1,2,3,4],[5,4,8,7],[10,11,12,13]
arr2 = np.array(j)
print(arr2)

[[ 1  2  3  4]
 [ 5  4  8  7]
 [10 11 12 13]]


In [13]:
print(arr1.ndim)
print(arr1.shape)

1
(3,)


In [14]:
print(arr2.ndim)
print(arr2.shape)

2
(3, 4)


In [15]:
type(arr1)
type(arr2)

numpy.ndarray

In [16]:
print(arr1.dtype)

int64


In [17]:
print(arr2.dtype)

int64


In [20]:
arr=np.array([2,3,3.5,'ac'])
print(arr)

['2' '3' '3.5' 'ac']


In [21]:
print(arr.dtype)

<U32


In [26]:
arr=np.array(['a','pdpu','r'])
print(arr)
print(type(arr))
print(arr.dtype)

['a' 'pdpu' 'r']
<class 'numpy.ndarray'>
<U4


In [25]:
arr[0]='rajat jain'
print(arr)

['raja' 'pdpu' 'r']


In [29]:
arr3=np.array(['a','pdpu','r',3])
print(arr3)
print(type(arr3))
print(arr3.dtype)

['a' 'pdpu' 'r' '3']
<class 'numpy.ndarray'>
<U21


In [30]:
arr3[0]='rajat jain'
print(arr3)

['rajat jain' 'pdpu' 'r' '3']


In [38]:
arr1

array([10,  3,  4])

In [41]:
arr1[0]="hello"

ValueError: invalid literal for int() with base 10: 'hello'

In [40]:
print(arr1)

[10  3  4]


In [36]:
arr=np.array(['a','ab','c'])
print(arr)

['a' 'ab' 'c']


In [37]:
arr[0]=100
print(arr)

['10' 'ab' 'c']


In [44]:
arr1[-3]

10

In [45]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  4,  8,  7],
       [10, 11, 12, 13]])

In [47]:
print("row",arr2[0])

row 4


In [50]:
print("%s is my first row "%arr2[0])

[1 2 3 4] is my first row 


In [53]:
print(arr2[-1][-1])

13


In [54]:
arr2[::-1,::-1]

array([[13, 12, 11, 10],
       [ 7,  8,  4,  5],
       [ 4,  3,  2,  1]])

Slicing

In [55]:
arr1

array([10,  3,  4])

In [61]:
# a[start:end:stop]
# a2[start:end:step,start:end:step]
arr1[1:2]

array([3])