In [3]:
import numpy as np

In [4]:
arr1 = np.random.rand(3,3)
arr1

array([[0.27781967, 0.47139994, 0.84011738],
       [0.93688724, 0.55674057, 0.06608149],
       [0.88336436, 0.32840229, 0.15258348]])

In [6]:
arr2 = np.random.randn(3,3)
arr2

array([[ 1.57378969, -0.05946123,  0.23403635],
       [ 0.85299913, -0.60966081,  0.35473297],
       [ 0.61138595, -0.36827657,  0.25619374]])

In [9]:
arr3 = np.random.randint(1,100)
arr3

37

In [19]:
arr = np.random.rand(10,10)
col = [2,4,5,6]
row = [1,3,7,9]

row = [1,4]
col = [3,5]
arr[row,col]

array([0.33767848, 0.14550304])

In [ ]:
# operations and functions on the array

In [40]:
arr1 = np.random.randint(0,10,(4,4))
arr2 = np.random.randint(0,10,(4,4))

In [41]:
arr1

array([[2, 7, 2, 5],
       [0, 0, 3, 8],
       [3, 4, 0, 8],
       [1, 3, 8, 8]])

In [42]:
arr2

array([[7, 1, 6, 5],
       [3, 6, 5, 5],
       [7, 3, 5, 5],
       [0, 4, 2, 2]])

In [43]:
arr1+arr2

array([[ 9,  8,  8, 10],
       [ 3,  6,  8, 13],
       [10,  7,  5, 13],
       [ 1,  7, 10, 10]])

In [44]:
arr1*arr2

array([[14,  7, 12, 25],
       [ 0,  0, 15, 40],
       [21, 12,  0, 40],
       [ 0, 12, 16, 16]])

In [45]:
arr1-arr2

array([[-5,  6, -4,  0],
       [-3, -6, -2,  3],
       [-4,  1, -5,  3],
       [ 1, -1,  6,  6]])

In [46]:
np.dot(arr1,arr2)

array([[49, 70, 67, 65],
       [21, 41, 31, 31],
       [33, 59, 54, 51],
       [72, 75, 77, 76]])

In [47]:
arr1

array([[2, 7, 2, 5],
       [0, 0, 3, 8],
       [3, 4, 0, 8],
       [1, 3, 8, 8]])

In [53]:
arr1.sum(axis=1)

array([16, 11, 15, 20])

In [54]:
arr1.prod()

0

In [55]:
arr1.max()

8

In [56]:
arr1.min()

0

In [57]:
arr1.max(axis=1)

array([7, 8, 8, 8])

In [58]:
arr1.mean()

3.875

In [59]:
arr1.std()

2.9764702249476644

In [60]:
arr1.var()

8.859375

In [63]:
np.median(arr1)

3.0

In [65]:
np.roll(arr1,1)

array([[8, 2, 7, 2],
       [5, 0, 0, 3],
       [8, 3, 4, 0],
       [8, 1, 3, 8]])

In [66]:
arr1.argmin()

4

In [67]:
arr1.argmax()

7

In [68]:
arr1.transpose()

array([[2, 0, 3, 1],
       [7, 0, 4, 3],
       [2, 3, 0, 8],
       [5, 8, 8, 8]])

In [69]:
np.sin(arr1)

array([[ 0.90929743,  0.6569866 ,  0.90929743, -0.95892427],
       [ 0.        ,  0.        ,  0.14112001,  0.98935825],
       [ 0.14112001, -0.7568025 ,  0.        ,  0.98935825],
       [ 0.84147098,  0.14112001,  0.98935825,  0.98935825]])

In [70]:
np.arcsin(arr1)

/var/folders/7v/x2pmyc1s7ln14fx8_29btn3c0000gn/T/ipykernel_23142/893717680.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(arr1)


array([[       nan,        nan,        nan,        nan],
       [0.        , 0.        ,        nan,        nan],
       [       nan,        nan, 0.        ,        nan],
       [1.57079633,        nan,        nan,        nan]])

In [71]:
arr1

array([[2, 7, 2, 5],
       [0, 0, 3, 8],
       [3, 4, 0, 8],
       [1, 3, 8, 8]])

In [72]:
np.exp(arr1)

array([[7.38905610e+00, 1.09663316e+03, 7.38905610e+00, 1.48413159e+02],
       [1.00000000e+00, 1.00000000e+00, 2.00855369e+01, 2.98095799e+03],
       [2.00855369e+01, 5.45981500e+01, 1.00000000e+00, 2.98095799e+03],
       [2.71828183e+00, 2.00855369e+01, 2.98095799e+03, 2.98095799e+03]])

In [73]:
np.exp2(arr1)

array([[  4., 128.,   4.,  32.],
       [  1.,   1.,   8., 256.],
       [  8.,  16.,   1., 256.],
       [  2.,   8., 256., 256.]])

In [74]:
np.power(3,arr1)

array([[   9, 2187,    9,  243],
       [   1,    1,   27, 6561],
       [  27,   81,    1, 6561],
       [   3,   27, 6561, 6561]])

In [75]:
np.log(arr1)

/var/folders/7v/x2pmyc1s7ln14fx8_29btn3c0000gn/T/ipykernel_23142/2108464003.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr1)


array([[0.69314718, 1.94591015, 0.69314718, 1.60943791],
       [      -inf,       -inf, 1.09861229, 2.07944154],
       [1.09861229, 1.38629436,       -inf, 2.07944154],
       [0.        , 1.09861229, 2.07944154, 2.07944154]])

In [77]:
np.log2(arr1)

/var/folders/7v/x2pmyc1s7ln14fx8_29btn3c0000gn/T/ipykernel_23142/3085764489.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(arr1)


array([[1.        , 2.80735492, 1.        , 2.32192809],
       [      -inf,       -inf, 1.5849625 , 3.        ],
       [1.5849625 , 2.        ,       -inf, 3.        ],
       [0.        , 1.5849625 , 3.        , 3.        ]])

In [78]:
arr1-arr1.mean()

array([[-1.875,  3.125, -1.875,  1.125],
       [-3.875, -3.875, -0.875,  4.125],
       [-0.875,  0.125, -3.875,  4.125],
       [-2.875, -0.875,  4.125,  4.125]])

In [79]:
arr1 

array([[2, 7, 2, 5],
       [0, 0, 3, 8],
       [3, 4, 0, 8],
       [1, 3, 8, 8]])

In [80]:
arr1 - arr1.mean(axis=0)

array([[ 0.5 ,  3.5 , -1.25, -2.25],
       [-1.5 , -3.5 , -0.25,  0.75],
       [ 1.5 ,  0.5 , -3.25,  0.75],
       [-0.5 , -0.5 ,  4.75,  0.75]])

In [81]:
arr1=np.random.randint(0,20,(5,6))
print(arr1)

[[17  8 12  8 10 19]
 [ 0 15  4 10  4 18]
 [11  3  8  3  7  7]
 [13  2 15  1 17 13]
 [ 1  9  2 10  0  1]]


# masking operation

In [85]:
arr1[arr1>5]

array([17,  8, 12,  8, 10, 19, 15, 10, 18, 11,  8,  7,  7, 13, 15, 17, 13,
        9, 10])

In [95]:
a=np.array([2,3,45,5])
b=np.array([2,3,45,5])

In [96]:
b

array([ 2,  3, 45,  5])

In [97]:
a==b

array([ True,  True,  True,  True])

In [98]:
arr1

array([[17,  8, 12,  8, 10, 19],
       [ 0, 15,  4, 10,  4, 18],
       [11,  3,  8,  3,  7,  7],
       [13,  2, 15,  1, 17, 13],
       [ 1,  9,  2, 10,  0,  1]])

In [102]:
np.sum(arr1>5,axis=1)

array([6, 3, 4, 4, 2])

In [103]:
np.sort(arr1)

array([[ 8,  8, 10, 12, 17, 19],
       [ 0,  4,  4, 10, 15, 18],
       [ 3,  3,  7,  7,  8, 11],
       [ 1,  2, 13, 13, 15, 17],
       [ 0,  1,  1,  2,  9, 10]])

In [4]:
arr1 = np.random.randint(0,10,(4,5))

In [5]:
arr1

array([[9, 0, 0, 3, 2],
       [1, 5, 8, 3, 3],
       [2, 0, 1, 4, 9],
       [5, 6, 7, 1, 2]])

In [32]:
arr1[]

array([[5, 6, 7, 1, 2],
       [2, 0, 1, 4, 9],
       [1, 5, 8, 3, 3],
       [9, 0, 0, 3, 2]])

In [27]:
arr1[::-1,1]

array([6, 0, 5, 0])