In [3]:
import numpy as np

In [9]:
arr1=np.array([2,10,15,45,10])
arr2=np.array([[2,10,15,45,10],[1,2,3,4,5],[6,5,7,78,2]])

In [10]:
arr2

array([[ 2, 10, 15, 45, 10],
       [ 1,  2,  3,  4,  5],
       [ 6,  5,  7, 78,  2]])

In [11]:
arr1[::]

array([ 2, 10, 15, 45, 10])

In [12]:
arr1[-1:]

array([10])

In [14]:
arr1[3:]

array([45, 10])

In [16]:
arr2[::]

array([[ 2, 10, 15, 45, 10],
       [ 1,  2,  3,  4,  5],
       [ 6,  5,  7, 78,  2]])

In [17]:
arr2[1::]

array([[ 1,  2,  3,  4,  5],
       [ 6,  5,  7, 78,  2]])

In [18]:
arr2[1:2:,2]

array([3])

In [19]:
arr2[1:2:,2:]

array([[3, 4, 5]])

In [20]:
arr2[::2]

array([[ 2, 10, 15, 45, 10],
       [ 6,  5,  7, 78,  2]])

In [21]:
arr2[::2,::2]

array([[ 2, 15, 10],
       [ 6,  7,  2]])

In [22]:
arr2[::,::2]

array([[ 2, 15, 10],
       [ 1,  3,  5],
       [ 6,  7,  2]])

In [24]:
arr2[1::-1,::-1]

array([[ 5,  4,  3,  2,  1],
       [10, 45, 15, 10,  2]])

In [25]:
arr2[::,::-1]

array([[10, 45, 15, 10,  2],
       [ 5,  4,  3,  2,  1],
       [ 2, 78,  7,  5,  6]])

In [ ]:
# access the element

In [26]:
arr1[0]

2

In [29]:
arr2[0] = -1
print(arr2)

[[-1 -1 -1 -1 -1]
 [ 1  2  3  4  5]
 [ 6  5  7 78  2]]


In [31]:
arr2[0] = -1,-2,-3,-4,-5
print(arr2)

[[-1 -2 -3 -4 -5]
 [ 1  2  3  4  5]
 [ 6  5  7 78  2]]


In [36]:
arr2[0][3] = -3
print(arr2)

[[-1 -2 -3 -3 -5]
 [ 1  2  3  4  5]
 [ 6  5  7 78  2]]


In [37]:
arr2[1,:]

array([1, 2, 3, 4, 5])

In [38]:
arr2[:,2]

array([-3,  3,  7])

In [41]:
arr2[:,-1]=-10

In [42]:
print(arr2)

[[ -1  -2  -3  -3 -10]
 [  1   2   3   4 -10]
 [  6   5   7  78 -10]]


In [45]:
# arr= np.array([[2,10,15,45,10],[1,2,3,4,5],[6,5,7,78,2]],dtype=complex)
print(arr)

[[ 2.+0.j 10.+0.j 15.+0.j 45.+0.j 10.+0.j]
 [ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j]
 [ 6.+0.j  5.+0.j  7.+0.j 78.+0.j  2.+0.j]]


In [72]:
arr3= np.array([[2,10,15,45,10],[1,2,3,4,5],[6,5,7,78,2]])
print(arr3)
slice1 =arr3[2::,::]
print('\n')
print(slice1)

[[ 2 10 15 45 10]
 [ 1  2  3  4  5]
 [ 6  5  7 78  2]]


[[ 6  5  7 78  2]]
140237154347600
140237153778832


In [73]:
slice1[0]=500
print(slice1)
print(arr3)

[[500 500 500 500 500]]
[[  2  10  15  45  10]
 [  1   2   3   4   5]
 [500 500 500 500 500]]


In [74]:
print(id(arr3))
print(id(slice1))

140237154255184
140237153778832


In [76]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
arr=np.linspace(1,20,5)
print(arr)

[ 1.    5.75 10.5  15.25 20.  ]


In [82]:
a = np.diag([2,3,4])
print(a)

[[2 0 0]
 [0 3 0]
 [0 0 4]]


In [83]:
np.diagonal(arr2)

array([-1,  2,  7])

In [84]:
arr2

array([[ -1,  -2,  -3,  -3, -10],
       [  1,   2,   3,   4, -10],
       [  6,   5,   7,  78, -10]])

In [87]:
a = np.zeros((3,5),dtype=float)
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [88]:
a = np.ones((3,5),dtype=float)
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
a = np.full((3,4),2.5)
a

array([[2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5]])

In [ ]:
# Concatenation

In [94]:
arr2

array([[ -1,  -2,  -3,  -3, -10],
       [  1,   2,   3,   4, -10],
       [  6,   5,   7,  78, -10]])

In [93]:
arr1

array([ 2, 10, 15, 45, 10])

In [99]:
arr1=np.arange(0,9).reshape((3,3))
arr2=np.arange(0,9).reshape((3,3))
arr=np.concatenate([arr1,arr2])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
arr1=np.arange(0,9).reshape((3,3))
arr2=np.arange(0,9).reshape((3,3))
arr=np.concatenate([arr1,arr2],axis=1)
arr

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [95]:
arr1=np.arange(0,5)
arr2=np.arange(0,5)
arr=np.concatenate([arr1,arr2])

In [96]:
print(arr)

[0 1 2 3 4 0 1 2 3 4]


In [112]:
arr1=np.arange(0,3)
arr2=np.arange(0,9).reshape((3,3))
arr=np.vstack([arr1,arr2])
arr

array([[0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [116]:
arr1= np.arange(0,3).reshape((3,-1))
arr=np.hstack([arr1,arr2])
arr

array([[0, 0, 1, 2],
       [1, 3, 4, 5],
       [2, 6, 7, 8]])

In [ ]:
# split

In [117]:
arr1

array([[0],
       [1],
       [2]])

In [129]:
arr1=np.arange(0,10)
arr2=np.arange(0,12).reshape((4,3))
arr=np.split(arr1,5)
a = arr[3]
print(arr)
print(a)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
[6 7]


In [130]:
arr=np.split(arr1,[2,4,8])
arr

[array([0, 1]), array([2, 3]), array([4, 5, 6, 7]), array([8, 9])]

In [131]:
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [133]:
arr=np.split(arr2,2)
arr

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [135]:
arr=np.split(arr2,[0,1])
arr

[array([], shape=(0, 3), dtype=int64),
 array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])]

In [136]:
arr=np.split(arr2,[0,1],axis=1)
arr

[array([], shape=(4, 0), dtype=int64),
 array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

In [ ]:
L = input("Enter multiple values\n").split(',')

In [ ]:
print(L)
arr = np.array(L).reshape(5,2)
print(arr)